"""SINGLE-FILE Flask backend for the "Category Formula Studio" Dataiku webapp.

Auto-generated by webapp/build_single.py (webapp_core/* + backend.py concatenated).
Paste this whole file into the webapp Python pane - no project-library setup needed.
Edit the source modules and re-run the builder rather than editing this file.
"""

from __future__ import annotations

import base64, hashlib, hmac, io, json, os, re, string, time, traceback, types
from datetime import datetime
from functools import wraps
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import openpyxl
from openpyxl.utils import get_column_letter
from flask import request, jsonify, Response



# ====================================================================================
# formula_translate
# ====================================================================================

"""Best-effort Excel-formula -> Python/pandas expression translator.

The output is a *suggestion*: the Admin UI shows it in an editable textarea next to the
original formula, and the admin fixes anything the translator could not handle. Every
generated expression runs in the restricted namespace built by ``compute.evaluate`` which
provides: ``df`` (canonical + already-computed columns), ``np``, ``pd``, the helpers
``IF AND OR NOT ROUND ROUNDUP ROUNDDOWN ABS INT MOD SQRT POWER MIN MAX SUM AVERAGE COUNT
CONCAT LEFT RIGHT MID LEN UPPER LOWER TRIM TEXT VALUE YEAR MONTH DAY TODAY NOW ISBLANK
ISNUMBER ISERROR IFERROR VLOOKUP CELL`` and ``PARAM`` (toggle/named-value accessor).

Formulas are expected in the *generalized* form produced by ``sample_parser`` where the
data row number has been replaced by the ``{r}`` placeholder (e.g. ``=C{r}*D{r}``).
"""


import re
from typing import Dict, List, Tuple

_TOKEN_SPEC = [
    ("WS", r"\s+"),
    ("STRING", r'"(?:[^"]|"")*"'),
    ("SHEETRANGE", r"(?:'[^']+'|[A-Za-z_][A-Za-z0-9_ ]*)!\$?[A-Za-z]{1,3}\$?\d+:\$?[A-Za-z]{1,3}\$?\d+"),
    ("SHEETCELL", r"(?:'[^']+'|[A-Za-z_][A-Za-z0-9_ ]*)!\$?[A-Za-z]{1,3}\$?\d+"),
    ("RELCELL", r"\$?[A-Za-z]{1,3}\{r\}"),
    ("ABSCELL", r"\$?[A-Za-z]{1,3}\$?\d+"),
    ("NUMBER", r"\d+(?:\.\d+)?(?:[eE][+-]?\d+)?"),
    ("FUNC", r"[A-Za-z_][A-Za-z0-9_.]*(?=\s*\()"),
    ("IDENT", r"[A-Za-z_][A-Za-z0-9_.]*"),
    ("OP", r"<>|<=|>=|[-+*/^&=<>]"),
    ("LPAREN", r"\("),
    ("RPAREN", r"\)"),
    ("COMMA", r","),
]
_MASTER_RE = re.compile("|".join(f"(?P<{n}>{p})" for n, p in _TOKEN_SPEC))

_FUNC_MAP = {
    "IF": "IF", "IFERROR": "IFERROR", "AND": "AND", "OR": "OR", "NOT": "NOT",
    "ROUND": "ROUND", "ROUNDUP": "ROUNDUP", "ROUNDDOWN": "ROUNDDOWN",
    "ABS": "ABS", "INT": "INT", "MOD": "MOD", "SQRT": "SQRT", "POWER": "POWER",
    "MIN": "MIN", "MAX": "MAX", "SUM": "SUM", "AVERAGE": "AVERAGE", "COUNT": "COUNT",
    "CONCAT": "CONCAT", "CONCATENATE": "CONCAT",
    "LEFT": "LEFT", "RIGHT": "RIGHT", "MID": "MID", "LEN": "LEN",
    "UPPER": "UPPER", "LOWER": "LOWER", "TRIM": "TRIM", "TEXT": "TEXT", "VALUE": "VALUE",
    "YEAR": "YEAR", "MONTH": "MONTH", "DAY": "DAY", "TODAY": "TODAY", "NOW": "NOW",
    "ISBLANK": "ISBLANK", "ISNUMBER": "ISNUMBER", "ISERROR": "ISERROR",
    "COALESCE": "IFERROR",
}


class _Tok:
    __slots__ = ("kind", "val")

    def __init__(self, kind: str, val: str):
        self.kind, self.val = kind, val

    def __repr__(self):  # pragma: no cover - debug only
        return f"{self.kind}:{self.val}"


def _tokenize(s: str) -> List[_Tok]:
    out: List[_Tok] = []
    pos = 0
    while pos < len(s):
        m = _MASTER_RE.match(s, pos)
        if not m:
            raise ValueError(f"Cannot tokenize near: {s[pos:pos + 20]!r}")
        pos = m.end()
        kind = m.lastgroup
        if kind == "WS":
            continue
        out.append(_Tok(kind, m.group()))
    return out


def _sheet_name(ref: str) -> str:
    name = ref.split("!", 1)[0]
    if name.startswith("'") and name.endswith("'"):
        name = name[1:-1]
    return name


class _Parser:
    def __init__(self, tokens: List[_Tok], header_by_letter: Dict[str, str]):
        self.toks = tokens
        self.i = 0
        self.headers = header_by_letter
        self.notes: List[str] = []

    # -- token helpers
    def _peek(self):
        return self.toks[self.i] if self.i < len(self.toks) else None

    def _next(self):
        t = self.toks[self.i]
        self.i += 1
        return t

    def _eat(self, kind):
        t = self._peek()
        if not t or t.kind != kind:
            raise ValueError(f"Expected {kind}, got {t}")
        return self._next()

    # -- grammar
    def parse(self) -> str:
        expr = self._concat()
        return expr

    def _concat(self) -> str:
        left = self._compare()
        while self._peek() and self._peek().kind == "OP" and self._peek().val == "&":
            self._next()
            right = self._compare()
            left = f"CONCAT({left}, {right})"
        return left

    def _compare(self) -> str:
        left = self._addsub()
        while self._peek() and self._peek().kind == "OP" and self._peek().val in ("=", "<>", "<", ">", "<=", ">="):
            op = self._next().val
            py = {"=": "==", "<>": "!="}.get(op, op)
            right = self._addsub()
            left = f"({left} {py} {right})"
        return left

    def _addsub(self) -> str:
        left = self._muldiv()
        while self._peek() and self._peek().kind == "OP" and self._peek().val in ("+", "-"):
            op = self._next().val
            right = self._muldiv()
            left = f"({left} {op} {right})"
        return left

    def _muldiv(self) -> str:
        left = self._power()
        while self._peek() and self._peek().kind == "OP" and self._peek().val in ("*", "/"):
            op = self._next().val
            right = self._power()
            left = f"({left} {op} {right})"
        return left

    def _power(self) -> str:
        left = self._unary()
        while self._peek() and self._peek().kind == "OP" and self._peek().val == "^":
            self._next()
            right = self._unary()
            left = f"({left} ** {right})"
        return left

    def _unary(self) -> str:
        t = self._peek()
        if t and t.kind == "OP" and t.val in ("-", "+"):
            self._next()
            return f"({t.val}{self._unary()})"
        return self._primary()

    def _primary(self) -> str:
        t = self._peek()
        if t is None:
            raise ValueError("Unexpected end of formula")
        if t.kind == "LPAREN":
            self._next()
            inner = self._concat()
            self._eat("RPAREN")
            return f"({inner})"
        if t.kind == "NUMBER":
            return self._next().val
        if t.kind == "STRING":
            raw = self._next().val[1:-1].replace('""', '"')
            return repr(raw)
        if t.kind == "FUNC":
            return self._funccall()
        if t.kind == "RELCELL":
            letter = self._next().val.split("{")[0].replace("$", "").upper()
            col = self.headers.get(letter)
            if col is None:
                self.notes.append(f"column letter {letter} not in the data schema")
                return f"df[{letter!r}]"
            return f"df[{col!r}]"
        if t.kind == "ABSCELL":
            self._next()
            self.notes.append(
                f"fixed cell {t.val} on the data sheet cannot be resolved at compute time"
            )
            return "np.nan"
        if t.kind == "SHEETCELL":
            self._next()
            sheet = _sheet_name(t.val)
            a1 = t.val.split("!", 1)[1].replace("$", "")
            return f"CELL({sheet!r}, {a1!r})"
        if t.kind == "SHEETRANGE":
            self._next()
            return f"LOOKUP_TABLE({_sheet_name(t.val)!r})"
        if t.kind == "IDENT":
            name = self._next().val
            if name.upper() in ("TRUE", "FALSE"):
                return name.capitalize()
            return f"PARAM({name!r})"
        raise ValueError(f"Unexpected token {t}")

    def _funccall(self) -> str:
        fname = self._next().val.upper()
        self._eat("LPAREN")
        raw_args: List[str] = []
        arg_tokens: List[List[_Tok]] = []
        if self._peek() and self._peek().kind != "RPAREN":
            while True:
                start = self.i
                val = self._concat()
                raw_args.append(val)
                arg_tokens.append(self.toks[start:self.i])
                if self._peek() and self._peek().kind == "COMMA":
                    self._next()
                    continue
                break
        self._eat("RPAREN")

        if fname == "VLOOKUP":
            # VLOOKUP(key, Sheet!range, col_index, [approx])
            sheet = None
            for tk in arg_tokens[1] if len(arg_tokens) > 1 else []:
                if tk.kind in ("SHEETRANGE", "SHEETCELL"):
                    sheet = _sheet_name(tk.val)
                    break
            key = raw_args[0] if raw_args else "np.nan"
            col_index = raw_args[2] if len(raw_args) > 2 else "2"
            approx = raw_args[3] if len(raw_args) > 3 else "False"
            if sheet is None:
                self.notes.append("VLOOKUP table is not a Sheet!range reference")
                sheet = "UNKNOWN"
            return f"VLOOKUP({key}, {sheet!r}, {col_index}, {approx})"

        if fname in ("HLOOKUP", "INDEX", "MATCH", "XLOOKUP", "LOOKUP"):
            self.notes.append(f"{fname} needs manual translation")
            return f"MANUAL({fname!r})"

        if fname in ("TRUE", "FALSE"):
            return fname.capitalize()

        if fname == "IFS":
            # IFS(c1,v1,c2,v2,...) -> nested IF
            self.notes.append("IFS converted to nested IF")
            expr = "np.nan"
            for k in range(len(raw_args) - 2, -1, -2):
                expr = f"IF({raw_args[k]}, {raw_args[k + 1]}, {expr})"
            return expr

        mapped = _FUNC_MAP.get(fname)
        if mapped is None:
            self.notes.append(f"unknown function {fname} kept as-is")
            mapped = fname
        return f"{mapped}({', '.join(raw_args)})"


def translate(excel_formula: str, header_by_letter: Dict[str, str]) -> Tuple[str, List[str]]:
    """Return ``(python_expression, notes)``. Never raises - failures land in ``notes``."""
    s = excel_formula.strip()
    if s.startswith("="):
        s = s[1:]
    if not s:
        return "np.nan", ["empty formula"]
    try:
        parser = _Parser(_tokenize(s), header_by_letter)
        expr = parser.parse()
        if parser.i != len(parser.toks):
            parser.notes.append("trailing tokens were ignored")
        return expr, parser.notes
    except Exception as exc:  # noqa: BLE001 - best effort, surface to admin
        return f"np.nan  # TODO translate: {s}", [f"could not parse: {exc}"]

formula_translate = types.SimpleNamespace(translate=translate)


# ====================================================================================
# sample_parser
# ====================================================================================

"""Analyse an uploaded sample workbook.

The sample ``.xlsx`` holds, on separate sheets:
  * one **data sheet** whose rows may start at any row (header auto-detected);
  * some columns of that data sheet contain **Excel formulas** -> "computed" columns;
  * other sheets are **lookup / mapping tables** referenced by the formulas;
  * formulas may reference **toggle** names that are neither columns nor lookup sheets.

``analyze_sample(bytes)`` returns a plain dict the Admin UI renders for review/editing.
Only openpyxl + (optional) the sibling ``formula_translate`` module are used - no dataiku.
"""


import io
import re
import string
from typing import Any, Dict, List, Optional, Tuple

import openpyxl


MAX_SCAN_ROWS = 40
_CELL_RE = re.compile(r"(\$?)([A-Za-z]{1,3})(\$?)(\d+)")
_SHEET_REF_RE = re.compile(r"(?:'([^']+)'|([A-Za-z_][A-Za-z0-9_ ]*))!")
_FUNC_RE = re.compile(r"([A-Za-z][A-Za-z0-9_.]*)\s*\(")
_TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# Excel built-ins we translate / recognise; never treated as toggles.
KNOWN_FUNCS = {
    "IF", "IFS", "IFERROR", "AND", "OR", "NOT", "ROUND", "ROUNDUP", "ROUNDDOWN",
    "ABS", "MIN", "MAX", "SUM", "AVERAGE", "COUNT", "INT", "MOD", "SQRT", "POWER",
    "VLOOKUP", "HLOOKUP", "INDEX", "MATCH", "LOOKUP", "XLOOKUP",
    "CONCAT", "CONCATENATE", "LEFT", "RIGHT", "MID", "LEN", "UPPER", "LOWER", "TRIM",
    "TEXT", "VALUE", "TODAY", "NOW", "YEAR", "MONTH", "DAY", "DATE", "TRUE", "FALSE",
    "ISBLANK", "ISNUMBER", "ISERROR", "COALESCE",
}


# --------------------------------------------------------------------------- utils
def col_letter_to_index(letter: str) -> int:
    """``A`` -> 0, ``B`` -> 1, ``AA`` -> 26 ..."""
    n = 0
    for ch in letter.upper():
        n = n * 26 + (ord(ch) - ord("A") + 1)
    return n - 1


def col_index_to_letter(idx: int) -> str:
    idx += 1
    out = ""
    while idx > 0:
        idx, rem = divmod(idx - 1, 26)
        out = string.ascii_uppercase[rem] + out
    return out


def _norm(v: Any) -> str:
    return re.sub(r"\s+", " ", str(v)).strip() if v is not None else ""


def _looks_like_label(v: Any) -> bool:
    s = _norm(v)
    if not s:
        return False
    try:
        float(s.replace(",", ""))
        return False
    except ValueError:
        return True


def detect_header_row(rows: List[List[Any]], max_scan: int = MAX_SCAN_ROWS) -> int:
    """Return the 0-based index of the most likely header row.

    Heuristic: the row with the most distinct non-empty text cells that also has a
    non-empty data row beneath it and no empty cells between its populated columns.
    """
    best_idx, best_score = 0, -1.0
    limit = min(len(rows), max_scan)
    for i in range(limit):
        row = rows[i]
        labels = [c for c in row if _looks_like_label(c)]
        non_null = [c for c in row if _norm(c)]
        if len(labels) < 2:
            continue
        nxt = rows[i + 1] if i + 1 < len(rows) else []
        has_data_below = any(_norm(c) for c in nxt)
        distinct = len({_norm(c).lower() for c in labels})
        score = distinct + 0.5 * len(non_null)
        if has_data_below:
            score += 3
        if len(labels) == len(non_null):  # header row is usually all-text
            score += 1
        if score > best_score:
            best_idx, best_score = i, score
    return best_idx


def _sheet_rows(ws, values_only: bool = True) -> List[List[Any]]:
    return [list(r) for r in ws.iter_rows(values_only=values_only)]


def _headers_from_row(row: List[Any]) -> List[str]:
    headers, seen = [], {}
    for j, cell in enumerate(row):
        name = _norm(cell) or f"Column{col_index_to_letter(j)}"
        if name in seen:
            seen[name] += 1
            name = f"{name}.{seen[name]}"
        else:
            seen[name] = 0
        headers.append(name)
    return headers


# ------------------------------------------------------------------- formula tools
def extract_refs(formula: str) -> Dict[str, List[str]]:
    """Split a formula into referenced sheet names, function names and bare tokens."""
    sheets = sorted({m.group(1) or m.group(2) for m in _SHEET_REF_RE.finditer(formula)})
    funcs = sorted({m.group(1).upper() for m in _FUNC_RE.finditer(formula)})
    # Strip string literals and sheet-qualified refs before scanning bare tokens.
    stripped = re.sub(r'"[^"]*"', "", formula)
    stripped = _SHEET_REF_RE.sub("", stripped)
    stripped = _CELL_RE.sub("", stripped)
    tokens = sorted(
        {
            t for t in _TOKEN_RE.findall(stripped)
            if t.upper() not in KNOWN_FUNCS and not re.fullmatch(r"[A-Za-z]{1,3}\d*", t)
        }
    )
    return {"sheets": sheets, "funcs": funcs, "tokens": tokens}


def generalize_formula(formula: str, row: int, header_letters: Dict[str, str]) -> str:
    """Replace same-sheet cell refs on ``row`` with the ``{r}`` placeholder.

    ``A5`` on row 5 -> ``A{r}``; absolute ``$A$5`` and other-sheet refs are left alone
    so they stay constant across rows.
    """
    def repl(m: re.Match) -> str:
        dollar_col, col, dollar_row, rownum = m.groups()
        # Leave alone if it is part of a sheet-qualified ref (handled by caller context).
        if dollar_row == "$":
            return m.group(0)
        if int(rownum) == row:
            return f"{dollar_col}{col}{{r}}"
        return m.group(0)

    # Protect sheet-qualified refs from row generalisation.
    placeholders: Dict[str, str] = {}

    def stash(m: re.Match) -> str:
        key = f"\x00{len(placeholders)}\x00"
        placeholders[key] = m.group(0)
        return key

    protected = re.sub(_SHEET_REF_RE.pattern + _CELL_RE.pattern, stash, formula)
    generalized = _CELL_RE.sub(repl, protected)
    for key, val in placeholders.items():
        generalized = generalized.replace(key, val)
    return generalized


# ------------------------------------------------------------------------- analyse
def analyze_sample(file_bytes: bytes, data_sheet: Optional[str] = None) -> Dict[str, Any]:
    """Parse the sample workbook. See module docstring for the return shape."""
    wb_f = openpyxl.load_workbook(io.BytesIO(file_bytes), data_only=False)
    wb_v = openpyxl.load_workbook(io.BytesIO(file_bytes), data_only=True)
    warnings: List[str] = []

    # 1. pick the data sheet: explicit choice, else the sheet with the most formula cells,
    #    else the sheet with the largest populated area.
    def formula_count(ws) -> int:
        c = 0
        for r in ws.iter_rows():
            for cell in r:
                if isinstance(cell.value, str) and cell.value.startswith("="):
                    c += 1
        return c

    sheet_names = wb_f.sheetnames
    if data_sheet and data_sheet in sheet_names:
        ds_name = data_sheet
    else:
        scored = sorted(
            sheet_names,
            key=lambda n: (formula_count(wb_f[n]), wb_f[n].max_row * wb_f[n].max_column),
            reverse=True,
        )
        ds_name = scored[0]
        if formula_count(wb_f[ds_name]) == 0:
            warnings.append(
                "No Excel formula cells were found on any sheet; "
                f"'{ds_name}' was chosen by size. Pick the data sheet manually if wrong."
            )

    ws_f, ws_v = wb_f[ds_name], wb_v[ds_name]
    frows = _sheet_rows(ws_f)
    vrows = _sheet_rows(ws_v)
    if not frows:
        raise ValueError(f"Data sheet '{ds_name}' is empty.")

    header_row = detect_header_row(vrows)
    headers = _headers_from_row(frows[header_row])
    letter_by_header = {h: col_index_to_letter(j) for j, h in enumerate(headers)}
    header_by_letter = {col_index_to_letter(j): h for j, h in enumerate(headers)}

    first_data = header_row + 1
    if first_data >= len(frows):
        raise ValueError(f"Data sheet '{ds_name}' has a header but no data rows.")

    # 2. classify columns
    canonical: List[str] = []
    computed: List[Dict[str, Any]] = []
    for j, name in enumerate(headers):
        formula_cell = None
        formula_excel_row = None
        for ridx in range(first_data, len(frows)):
            val = frows[ridx][j] if j < len(frows[ridx]) else None
            if isinstance(val, str) and val.startswith("="):
                formula_cell = val
                formula_excel_row = ridx + 1  # openpyxl rows are 1-based
                break
        if formula_cell is None:
            canonical.append(name)
            continue
        generalized = generalize_formula(formula_cell, formula_excel_row, letter_by_header)
        pandas_expr, xl_notes = formula_translate.translate(
            generalized, header_by_letter
        )
        refs = extract_refs(generalized)
        computed.append(
            {
                "name": name,
                "position": j,
                "excel_formula": generalized,
                "sample_excel_formula": formula_cell,
                "pandas_expr": pandas_expr,
                "refs": refs,
                "notes": xl_notes,
            }
        )

    if not computed:
        warnings.append("No computed (formula) columns detected on the data sheet.")

    # 3. lookup sheets = every other sheet
    lookups: List[Dict[str, Any]] = []
    for name in sheet_names:
        if name == ds_name:
            continue
        lrows = _sheet_rows(wb_v[name])
        if not any(any(_norm(c) for c in row) for row in lrows):
            continue
        lhr = detect_header_row(lrows)
        lheaders = _headers_from_row(lrows[lhr]) if lrows else []
        preview = [
            {lheaders[k]: row[k] if k < len(row) else None for k in range(len(lheaders))}
            for row in lrows[lhr + 1: lhr + 6]
        ]
        lookups.append(
            {
                "sheet": name,
                "header_row": lhr,
                "columns": lheaders,
                "preview": preview,
                "n_rows": max(0, len(lrows) - lhr - 1),
            }
        )
    lookup_sheet_names = {l["sheet"] for l in lookups}

    # 4. unresolved tokens -> toggle candidates
    canon_lower = {c.lower() for c in canonical}
    comp_lower = {c["name"].lower() for c in computed}
    toggles: List[str] = []
    for c in computed:
        for tok in c["refs"]["tokens"]:
            tl = tok.lower()
            if tl in canon_lower or tl in comp_lower:
                continue
            if tok in lookup_sheet_names:
                continue
            if tok not in toggles:
                toggles.append(tok)
        for sh in c["refs"]["sheets"]:
            if sh not in lookup_sheet_names:
                warnings.append(
                    f"Column '{c['name']}' references sheet '{sh}' which is not a "
                    "lookup sheet in the workbook."
                )

    # 5. name-collision guard (computed columns must be distinct from data columns)
    collisions = comp_lower & canon_lower
    if collisions:
        warnings.append(
            "Computed columns reuse data-column names: "
            + ", ".join(sorted(collisions))
            + ". Rename them so comparisons can address each side."
        )

    return {
        "sheets": sheet_names,
        "data_sheet": ds_name,
        "header_row": header_row,
        "canonical_schema": canonical,
        "computed_columns": computed,
        "lookups": lookups,
        "toggles": [{"name": t, "value": "Yes"} for t in toggles],
        "warnings": warnings,
    }


def sheet_to_records(file_bytes: bytes, sheet: str) -> Tuple[List[str], List[Dict[str, Any]]]:
    """Return ``(headers, rows-as-dicts)`` for one sheet, header auto-detected.

    Used by the backend to persist each lookup sheet into the mapping folder.
    """
    wb = openpyxl.load_workbook(io.BytesIO(file_bytes), data_only=True)
    rows = _sheet_rows(wb[sheet])
    hr = detect_header_row(rows)
    headers = _headers_from_row(rows[hr]) if rows else []
    records = []
    for row in rows[hr + 1:]:
        if not any(_norm(c) for c in row):
            continue
        records.append(
            {headers[k]: (row[k] if k < len(row) else None) for k in range(len(headers))}
        )
    return headers, records

# ====================================================================================
# compute
# ====================================================================================

"""Validate an input file against a category recipe, evaluate the computed columns and
build the output workbook (canonical values + **live Excel formulas** in the computed
columns + lookup sheets + a Parameters sheet).

Pure module: inputs are bytes / dicts, outputs are bytes / DataFrames. No ``dataiku``.
"""


import io
import re
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import openpyxl
from openpyxl.utils import get_column_letter


_A1_RE = re.compile(r"^\$?([A-Za-z]{1,3})\$?(\d+)$")


# --------------------------------------------------------------------------- input IO
def read_table(file_bytes: bytes, filename: str) -> Tuple[pd.DataFrame, int]:
    """Read csv / xls / xlsx into a DataFrame, auto-detecting the header row."""
    name = (filename or "").lower()
    if name.endswith(".csv") or name.endswith(".txt"):
        raw = pd.read_csv(io.BytesIO(file_bytes), header=None, dtype=object,
                          keep_default_na=False, skip_blank_lines=False)
        rows = raw.values.tolist()
    else:
        engine = "xlrd" if name.endswith(".xls") else "openpyxl"
        raw = pd.read_excel(io.BytesIO(file_bytes), header=None, dtype=object, engine=engine)
        rows = raw.values.tolist()
    if not rows:
        raise ValueError(f"{filename}: no rows found")
    hr = detect_header_row([[None if pd.isna(c) else c for c in r] for r in rows])
    headers = _headers_from_row(rows[hr])
    body = rows[hr + 1:]
    df = pd.DataFrame(body, columns=headers)
    df = df.dropna(axis=0, how="all").reset_index(drop=True)
    # trim trailing all-empty columns produced by ragged sheets
    df = df.loc[:, [not (h.startswith("Column") and df[h].isna().all()) for h in df.columns]]
    return df, hr


def validate_schema(columns: List[str], canonical_schema: List[str]) -> Dict[str, Any]:
    """Exact match: same columns, same order, nothing extra (case/space-insensitive)."""
    def key(s: str) -> str:
        return re.sub(r"\s+", " ", str(s)).strip().lower()

    got = [key(c) for c in columns]
    want = [key(c) for c in canonical_schema]
    got_set, want_set = set(got), set(want)
    missing = [c for c in canonical_schema if key(c) not in got_set]
    extra = [c for c in columns if key(c) not in want_set]
    order_ok = got == want
    ok = not missing and not extra and order_ok
    if ok:
        msg = "Schema matches."
    else:
        parts = []
        if missing:
            parts.append("missing: " + ", ".join(missing))
        if extra:
            parts.append("unexpected: " + ", ".join(extra))
        if not missing and not extra and not order_ok:
            parts.append("column order differs from the sample")
        msg = "; ".join(parts)
    return {"ok": ok, "missing": missing, "extra": extra,
            "order_ok": order_ok, "message": msg}


# ------------------------------------------------------------------------- lookups
class Lookups:
    """Access to the category's lookup tables (persisted from the sample's mapping sheets).

    ``tables`` maps sheet name -> ``{"headers": [...], "records": [ {..}, .. ],
    "header_row": int}``.
    """

    def __init__(self, tables: Dict[str, Dict[str, Any]]):
        self._t = tables or {}
        self._df_cache: Dict[str, pd.DataFrame] = {}
        self._grid_cache: Dict[str, List[List[Any]]] = {}

    def has(self, name: str) -> bool:
        return name in self._t

    def df(self, name: str) -> pd.DataFrame:
        if name not in self._df_cache:
            spec = self._t.get(name)
            if not spec:
                raise KeyError(f"lookup sheet '{name}' is not defined for this category")
            self._df_cache[name] = pd.DataFrame(spec["records"], columns=spec["headers"])
        return self._df_cache[name]

    def grid(self, name: str) -> List[List[Any]]:
        if name not in self._grid_cache:
            spec = self._t[name]
            hr = int(spec.get("header_row", 0))
            grid: List[List[Any]] = [[] for _ in range(hr)]
            grid.append(list(spec["headers"]))
            for rec in spec["records"]:
                grid.append([rec.get(h) for h in spec["headers"]])
            self._grid_cache[name] = grid
        return self._grid_cache[name]

    def cell(self, name: str, a1: str) -> Any:
        m = _A1_RE.match(a1.strip())
        if not m:
            raise ValueError(f"bad cell reference {a1!r}")
        col = col_letter_to_index(m.group(1))
        row = int(m.group(2)) - 1
        grid = self.grid(name)
        if row < len(grid) and col < len(grid[row]):
            return grid[row][col]
        return np.nan

    def vlookup(self, key, name: str, col_index: int, approximate: bool = False):
        frame = self.df(name)
        if frame.shape[1] < col_index:
            raise ValueError(f"VLOOKUP col index {col_index} out of range for '{name}'")
        keys = frame.iloc[:, 0]
        vals = frame.iloc[:, int(col_index) - 1]
        mapping = dict(zip(keys, vals))
        if isinstance(key, pd.Series):
            if approximate:
                sorted_keys = np.sort(keys.values)
                idx = np.searchsorted(sorted_keys, key.values, side="right") - 1
                idx = np.clip(idx, 0, len(sorted_keys) - 1)
                approx_keys = sorted_keys[idx]
                return pd.Series([mapping.get(k, np.nan) for k in approx_keys],
                                 index=key.index)
            return key.map(mapping)
        return mapping.get(key, np.nan)


# ---------------------------------------------------------------- eval helper funcs
def _series_index(*args):
    for a in args:
        if isinstance(a, pd.Series):
            return a.index
    return None


def _as_frame(args, index):
    cols = []
    for a in args:
        cols.append(a if isinstance(a, pd.Series) else pd.Series([a] * len(index), index=index))
    return pd.concat(cols, axis=1)


def IF(cond, a, b):
    idx = _series_index(cond, a, b)
    if idx is not None:
        return pd.Series(np.where(cond, a, b), index=idx)
    return a if cond else b


def IFERROR(value, fallback):
    if isinstance(value, pd.Series):
        return value.where(value.notna() & ~value.isin([np.inf, -np.inf]), fallback)
    try:
        if value is None or (isinstance(value, float) and (np.isnan(value) or np.isinf(value))):
            return fallback
        return value
    except TypeError:
        return value


def _reduce_logical(op, args, empty):
    idx = _series_index(*args)
    if idx is None:
        res = empty
        for a in args:
            res = op(res, bool(a))
        return res
    frame = _as_frame(args, idx).astype(bool)
    out = frame.iloc[:, 0]
    for c in range(1, frame.shape[1]):
        out = op(out, frame.iloc[:, c])
    return out


def AND(*args):
    return _reduce_logical(np.logical_and, args, True)


def OR(*args):
    return _reduce_logical(np.logical_or, args, False)


def NOT(x):
    return ~x if isinstance(x, pd.Series) else (not x)


def _rowwise(func, args):
    idx = _series_index(*args)
    if idx is None:
        return func([a for a in args])
    return _as_frame(args, idx).apply(lambda r: func(list(r.values)), axis=1)


def MIN(*a):
    return _rowwise(lambda xs: np.nanmin(pd.to_numeric(pd.Series(xs), errors="coerce")), a)


def MAX(*a):
    return _rowwise(lambda xs: np.nanmax(pd.to_numeric(pd.Series(xs), errors="coerce")), a)


def SUM(*a):
    return _rowwise(lambda xs: np.nansum(pd.to_numeric(pd.Series(xs), errors="coerce")), a)


def AVERAGE(*a):
    return _rowwise(lambda xs: np.nanmean(pd.to_numeric(pd.Series(xs), errors="coerce")), a)


def COUNT(*a):
    return _rowwise(lambda xs: pd.to_numeric(pd.Series(xs), errors="coerce").notna().sum(), a)


def ROUND(x, n=0):
    return np.round(pd.to_numeric(x, errors="coerce") if isinstance(x, pd.Series) else x, int(n))


def ROUNDUP(x, n=0):
    f = 10 ** int(n)
    return np.ceil((x if not isinstance(x, pd.Series) else pd.to_numeric(x, errors="coerce")) * f) / f


def ROUNDDOWN(x, n=0):
    f = 10 ** int(n)
    return np.floor((x if not isinstance(x, pd.Series) else pd.to_numeric(x, errors="coerce")) * f) / f


def ABS(x):
    return x.abs() if isinstance(x, pd.Series) else abs(x)


def INT(x):
    return np.floor(pd.to_numeric(x, errors="coerce")) if isinstance(x, pd.Series) else int(x)


def MOD(a, b):
    return a % b


def SQRT(x):
    return np.sqrt(x)


def POWER(x, p):
    return x ** p


def _str_series(x):
    return x.astype("string") if isinstance(x, pd.Series) else pd.Series([str(x)])


def CONCAT(*args):
    idx = _series_index(*args)
    if idx is None:
        return "".join("" if a is None else str(a) for a in args)
    frame = _as_frame(args, idx)
    return frame.apply(lambda r: "".join("" if v is None else str(v) for v in r.values), axis=1)


def LEFT(x, n=1):
    return x.astype("string").str[: int(n)] if isinstance(x, pd.Series) else str(x)[: int(n)]


def RIGHT(x, n=1):
    return x.astype("string").str[-int(n):] if isinstance(x, pd.Series) else str(x)[-int(n):]


def MID(x, start, length):
    s = int(start) - 1
    if isinstance(x, pd.Series):
        return x.astype("string").str[s: s + int(length)]
    return str(x)[s: s + int(length)]


def LEN(x):
    return x.astype("string").str.len() if isinstance(x, pd.Series) else len(str(x))


def UPPER(x):
    return x.astype("string").str.upper() if isinstance(x, pd.Series) else str(x).upper()


def LOWER(x):
    return x.astype("string").str.lower() if isinstance(x, pd.Series) else str(x).lower()


def TRIM(x):
    return x.astype("string").str.strip() if isinstance(x, pd.Series) else str(x).strip()


def TEXT(x, _fmt=None):
    return x.astype("string") if isinstance(x, pd.Series) else str(x)


def VALUE(x):
    return pd.to_numeric(x, errors="coerce")


def _dt(x):
    return pd.to_datetime(x, errors="coerce")


def YEAR(x):
    return _dt(x).dt.year if isinstance(x, pd.Series) else _dt(x).year


def MONTH(x):
    return _dt(x).dt.month if isinstance(x, pd.Series) else _dt(x).month


def DAY(x):
    return _dt(x).dt.day if isinstance(x, pd.Series) else _dt(x).day


def TODAY():
    return pd.Timestamp.today().normalize()


def NOW():
    return pd.Timestamp.now()


def ISBLANK(x):
    return x.isna() | (x.astype("string").str.len() == 0) if isinstance(x, pd.Series) else (x is None or x == "")


def ISNUMBER(x):
    return pd.to_numeric(x, errors="coerce").notna() if isinstance(x, pd.Series) else isinstance(x, (int, float))


def ISERROR(x):
    return x.isna() if isinstance(x, pd.Series) else (x is None)


# ------------------------------------------------------------------------- evaluate
def _toggle_value(raw: Any) -> Any:
    if isinstance(raw, str):
        low = raw.strip().lower()
        if low in ("yes", "true", "y", "1"):
            return True
        if low in ("no", "false", "n", "0", ""):
            return False
    return raw


def evaluate(df: pd.DataFrame, recipe: Dict[str, Any],
             lookups: Optional[Lookups] = None) -> pd.DataFrame:
    """Return a copy of ``df`` with the recipe's computed columns appended (values)."""
    lookups = lookups or Lookups({})
    toggles = {t["name"]: _toggle_value(t.get("value")) for t in recipe.get("toggles", [])}
    work = df.copy()
    # numeric coercion for canonical columns keeps arithmetic sane; keep original too.
    ns = {
        "np": np, "pd": pd, "df": work,
        "IF": IF, "IFERROR": IFERROR, "AND": AND, "OR": OR, "NOT": NOT,
        "MIN": MIN, "MAX": MAX, "SUM": SUM, "AVERAGE": AVERAGE, "COUNT": COUNT,
        "ROUND": ROUND, "ROUNDUP": ROUNDUP, "ROUNDDOWN": ROUNDDOWN, "ABS": ABS,
        "INT": INT, "MOD": MOD, "SQRT": SQRT, "POWER": POWER,
        "CONCAT": CONCAT, "LEFT": LEFT, "RIGHT": RIGHT, "MID": MID, "LEN": LEN,
        "UPPER": UPPER, "LOWER": LOWER, "TRIM": TRIM, "TEXT": TEXT, "VALUE": VALUE,
        "YEAR": YEAR, "MONTH": MONTH, "DAY": DAY, "TODAY": TODAY, "NOW": NOW,
        "ISBLANK": ISBLANK, "ISNUMBER": ISNUMBER, "ISERROR": ISERROR,
        "CELL": lookups.cell,
        "VLOOKUP": lambda key, sheet, col_index, approx=False: lookups.vlookup(
            key, sheet, col_index, bool(approx)),
        "LOOKUP_TABLE": lookups.df,
        "PARAM": lambda name: toggles.get(name, toggles.get(str(name), np.nan)),
        "MANUAL": lambda fn: (_ for _ in ()).throw(
            ValueError(f"formula uses {fn} which needs a manual pandas expression")),
    }
    errors: List[str] = []
    for col in sorted(recipe.get("computed_columns", []), key=lambda c: c.get("position", 1e9)):
        expr = col.get("pandas_expr") or "np.nan"
        try:
            result = eval(expr, {"__builtins__": {}}, ns)  # noqa: S307 - trusted admin config
        except Exception as exc:  # noqa: BLE001
            errors.append(f"{col['name']}: {exc}")
            result = np.nan
        work[col["name"]] = result
        ns["df"] = work
    if errors:
        work.attrs["compute_errors"] = errors
    return work


# -------------------------------------------------------------------- output workbook
def ordered_columns(recipe: Dict[str, Any]) -> List[str]:
    canonical = list(recipe.get("canonical_schema", []))
    computed = sorted(recipe.get("computed_columns", []), key=lambda c: c.get("position", 1e9))
    total = len(canonical) + len(computed)
    slots: List[Optional[str]] = [None] * total
    for c in computed:
        pos = c.get("position")
        if isinstance(pos, int) and 0 <= pos < total and slots[pos] is None:
            slots[pos] = c["name"]
    it = iter(canonical)
    for i in range(total):
        if slots[i] is None:
            slots[i] = next(it, None)
    # any leftovers (bad positions) appended
    leftover = [c["name"] for c in computed if c["name"] not in slots] + [c for c in it]
    return [s for s in slots if s] + leftover


def build_workbook(values_df: pd.DataFrame, recipe: Dict[str, Any],
                   lookups: Optional[Lookups] = None,
                   data_sheet_name: str = "Data") -> bytes:
    """Build the output ``.xlsx``: computed columns carry the live Excel formula."""
    lookups = lookups or Lookups({})
    cols = [c for c in ordered_columns(recipe) if c in values_df.columns] or list(values_df.columns)
    computed_by_name = {c["name"]: c for c in recipe.get("computed_columns", [])}

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = data_sheet_name[:31]
    ws.append(cols)
    for r_off, (_, row) in enumerate(values_df.iterrows()):
        excel_row = r_off + 2
        out_row = []
        for c in cols:
            if c in computed_by_name:
                formula = computed_by_name[c].get("excel_formula", "")
                out_row.append(formula.replace("{r}", str(excel_row)) if formula else row.get(c))
            else:
                val = row.get(c)
                out_row.append(None if (isinstance(val, float) and np.isnan(val)) else val)
        ws.append(out_row)

    # lookup sheets
    for name, spec in getattr(lookups, "_t", {}).items():
        sh = wb.create_sheet(title=str(name)[:31])
        for _ in range(int(spec.get("header_row", 0))):
            sh.append([])
        sh.append(list(spec["headers"]))
        for rec in spec["records"]:
            sh.append([rec.get(h) for h in spec["headers"]])

    # parameters
    toggles = recipe.get("toggles", [])
    if toggles:
        ps = wb.create_sheet(title="Parameters")
        ps.append(["Name", "Value"])
        for t in toggles:
            ps.append([t["name"], t.get("value")])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def lookups_from_sample(analysis: Dict[str, Any], file_bytes: bytes) -> Dict[str, Dict[str, Any]]:
    """Build the persisted lookup-table spec dict from a sample analysis + the file bytes."""
    tables: Dict[str, Dict[str, Any]] = {}
    for lk in analysis.get("lookups", []):
        headers, records = sheet_to_records(file_bytes, lk["sheet"])
        tables[lk["sheet"]] = {
            "headers": headers, "records": records,
            "header_row": lk.get("header_row", 0),
        }
    return tables

# ====================================================================================
# compare
# ====================================================================================

"""Row-level comparison of configured column pairs across every computed output file.

A comparison rule (configured in the Admin UI) is::

    { "left": "<computed column>", "right": "<other column>",
      "type": "numeric" | "text", "tolerance": 0.01 }

For each row of each file every rule is evaluated; the row is *matched* only when all
rules pass. ``build_comparison_workbook`` returns one ``.xlsx`` with ``Matched``,
``Mismatched`` and ``Summary`` sheets.
"""


import io
from datetime import datetime
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd
import openpyxl


def _num(x):
    return pd.to_numeric(pd.Series([x]), errors="coerce").iloc[0]


def _cmp_cell(left: Any, right: Any, rule: Dict[str, Any]) -> Tuple[bool, float]:
    rtype = rule.get("type", "numeric")
    if rtype == "numeric":
        lv, rv = _num(left), _num(right)
        if pd.isna(lv) and pd.isna(rv):
            return True, 0.0
        if pd.isna(lv) or pd.isna(rv):
            return False, float("nan")
        delta = abs(float(lv) - float(rv))
        return delta <= float(rule.get("tolerance", 0) or 0), delta
    ls = "" if left is None or (isinstance(left, float) and np.isnan(left)) else str(left).strip()
    rs = "" if right is None or (isinstance(right, float) and np.isnan(right)) else str(right).strip()
    if not rule.get("case_sensitive"):
        ls, rs = ls.lower(), rs.lower()
    return ls == rs, 0.0 if ls == rs else float("nan")


def compare_file(filename: str, values_df: pd.DataFrame,
                 rules: List[Dict[str, Any]], key_columns: List[str] | None = None
                 ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    matched: List[Dict[str, Any]] = []
    mismatched: List[Dict[str, Any]] = []
    key_columns = [k for k in (key_columns or []) if k in values_df.columns]

    for pos, (_, row) in enumerate(values_df.iterrows()):
        excel_row = pos + 2
        key_part = {f"key:{k}": row.get(k) for k in key_columns}
        row_ok = True
        row_details: List[Dict[str, Any]] = []
        for rule in rules:
            lcol, rcol = rule.get("left"), rule.get("right")
            if lcol not in values_df.columns or rcol not in values_df.columns:
                row_ok = False
                row_details.append({"rule": f"{lcol} vs {rcol}", "status": "column missing"})
                continue
            ok, delta = _cmp_cell(row.get(lcol), row.get(rcol), rule)
            row_ok = row_ok and ok
            row_details.append({
                "rule": f"{lcol} vs {rcol}", "status": "ok" if ok else "diff",
                "left_col": lcol, "left_val": row.get(lcol),
                "right_col": rcol, "right_val": row.get(rcol),
                "delta": None if (isinstance(delta, float) and np.isnan(delta)) else delta,
            })
        base = {"source_file": filename, "row": excel_row, **key_part}
        if row_ok:
            matched.append({**base, **{d["rule"]: "ok" for d in row_details}})
        else:
            for d in row_details:
                if d["status"] != "ok":
                    mismatched.append({**base, **d})
    return matched, mismatched


def run_comparison(files: List[Tuple[str, pd.DataFrame]], recipe: Dict[str, Any]
                   ) -> Dict[str, pd.DataFrame]:
    rules = recipe.get("comparison", [])
    key_columns = recipe.get("comparison_keys", [])
    all_matched: List[Dict[str, Any]] = []
    all_mismatched: List[Dict[str, Any]] = []
    summary: List[Dict[str, Any]] = []

    for filename, vdf in files:
        m, mm = compare_file(filename, vdf, rules, key_columns)
        all_matched.extend(m)
        all_mismatched.extend(mm)
        mismatch_rows = {(d["source_file"], d["row"]) for d in mm}
        summary.append({
            "source_file": filename,
            "rows": len(vdf),
            "matched_rows": len(m),
            "mismatched_rows": len(mismatch_rows),
            "mismatch_findings": len(mm),
        })

    return {
        "Matched": pd.DataFrame(all_matched),
        "Mismatched": pd.DataFrame(all_mismatched),
        "Summary": pd.DataFrame(summary),
    }


def build_comparison_workbook(files: List[Tuple[str, pd.DataFrame]],
                              recipe: Dict[str, Any]) -> bytes:
    sheets = run_comparison(files, recipe)
    wb = openpyxl.Workbook()
    wb.remove(wb.active)
    order = ["Summary", "Matched", "Mismatched"]
    for name in order:
        frame = sheets.get(name, pd.DataFrame())
        ws = wb.create_sheet(title=name)
        if frame.empty:
            ws.append([f"(no {name.lower()} rows)"])
            continue
        ws.append(list(frame.columns))
        for _, row in frame.iterrows():
            ws.append([
                None if (isinstance(v, float) and np.isnan(v)) else
                (v.item() if hasattr(v, "item") else v)
                for v in row.values
            ])
    meta = wb.create_sheet(title="_meta")
    meta.append(["generated", datetime.utcnow().isoformat() + "Z"])
    meta.append(["category", recipe.get("name", recipe.get("id", ""))])
    meta.append(["rules", "; ".join(f"{r.get('left')} vs {r.get('right')}"
                                    for r in recipe.get("comparison", []))])
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()

# ====================================================================================
# auth
# ====================================================================================

"""Admin authentication: pbkdf2 password hashing + stateless HMAC session tokens.

Credentials are seeded from :data:`DEFAULT_ADMIN_USERNAME` / :data:`DEFAULT_ADMIN_PASSWORD`
and then persisted (hashed) in the config folder by ``config_store``; the admin changes
them from the Admin page.
"""


import base64
import hashlib
import hmac
import json
import os
import time
from typing import Any, Dict, Optional, Tuple

DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = "changeme"  # forced change on first successful login
_PBKDF2_ROUNDS = 200_000
TOKEN_TTL_SECONDS = 8 * 3600


def _b64e(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64d(txt: str) -> bytes:
    return base64.urlsafe_b64decode(txt + "=" * (-len(txt) % 4))


def hash_password(password: str, salt_hex: Optional[str] = None) -> Tuple[str, str]:
    salt = bytes.fromhex(salt_hex) if salt_hex else os.urandom(16)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, _PBKDF2_ROUNDS)
    return salt.hex(), dk.hex()


def verify_password(password: str, salt_hex: str, hash_hex: str) -> bool:
    _, calc = hash_password(password, salt_hex)
    return hmac.compare_digest(calc, hash_hex)


def default_admin() -> Dict[str, Any]:
    salt, h = hash_password(DEFAULT_ADMIN_PASSWORD)
    return {"username": DEFAULT_ADMIN_USERNAME, "salt": salt, "hash": h,
            "must_change": True}


def make_token(username: str, secret: str, now: Optional[float] = None) -> str:
    payload = {"u": username, "exp": int((now or time.time()) + TOKEN_TTL_SECONDS)}
    body = _b64e(json.dumps(payload, separators=(",", ":")).encode("utf-8"))
    sig = _b64e(hmac.new(secret.encode("utf-8"), body.encode("ascii"), hashlib.sha256).digest())
    return f"{body}.{sig}"


def verify_token(token: str, secret: str, now: Optional[float] = None) -> Optional[str]:
    try:
        body, sig = token.split(".", 1)
        expected = _b64e(hmac.new(secret.encode("utf-8"), body.encode("ascii"),
                                  hashlib.sha256).digest())
        if not hmac.compare_digest(sig, expected):
            return None
        payload = json.loads(_b64d(body))
        if payload.get("exp", 0) < (now or time.time()):
            return None
        return payload.get("u")
    except Exception:  # noqa: BLE001
        return None


def new_secret() -> str:
    return os.urandom(32).hex()

auth = types.SimpleNamespace(default_admin=default_admin, new_secret=new_secret,
    hash_password=hash_password, verify_password=verify_password,
    make_token=make_token, verify_token=verify_token)


# ====================================================================================
# config_store
# ====================================================================================

"""Persistence for the webapp.

* App settings + per-category recipes live as JSON in a **dedicated config managed
  folder**. Its id comes from the project variable ``WEBAPP_CONFIG_FOLDER`` (or the
  ``WEBAPP_CONFIG_FOLDER`` env var / the ``CONFIG_FOLDER_FALLBACK`` constant below).
* Category input / mapping / output / template files live in the four managed folders
  the admin wires to each category.

When ``dataiku`` is unavailable (local tests) everything degrades to a local directory
tree rooted at ``$WEBAPP_LOCAL_ROOT`` (default: ``./_webapp_local``).
"""


import io
import json
import os
import string
from typing import Any, Dict, List, Optional


CONFIG_FOLDER_FALLBACK = ""  # set to a managed-folder id to hard-wire it
SETTINGS_FILE = "app_settings.json"
N_DEFAULT_CATEGORIES = 9

try:  # pragma: no cover - exercised only inside Dataiku
    import dataiku
    _HAS_DATAIKU = True
except Exception:  # noqa: BLE001
    dataiku = None
    _HAS_DATAIKU = False


# --------------------------------------------------------------------------- backends
class _LocalFolder:
    def __init__(self, root: str):
        self.root = root
        os.makedirs(root, exist_ok=True)

    def _p(self, path: str) -> str:
        return os.path.join(self.root, path.lstrip("/"))

    def list_paths(self) -> List[str]:
        out = []
        for base, _, files in os.walk(self.root):
            for f in files:
                out.append("/" + os.path.relpath(os.path.join(base, f), self.root).replace("\\", "/"))
        return out

    def read_bytes(self, path: str) -> bytes:
        with open(self._p(path), "rb") as fh:
            return fh.read()

    def write_bytes(self, path: str, data: bytes) -> None:
        full = self._p(path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "wb") as fh:
            fh.write(data)

    def delete(self, path: str) -> None:
        try:
            os.remove(self._p(path))
        except FileNotFoundError:
            pass


class _DkuFolder:  # pragma: no cover - exercised only inside Dataiku
    def __init__(self, folder_id: str):
        self.f = dataiku.Folder(folder_id)

    def list_paths(self) -> List[str]:
        return self.f.list_paths_in_partition()

    def read_bytes(self, path: str) -> bytes:
        with self.f.get_download_stream(path) as s:
            return s.read()

    def write_bytes(self, path: str, data: bytes) -> None:
        self.f.upload_stream(path, io.BytesIO(data))

    def delete(self, path: str) -> None:
        try:
            self.f.delete_path(path)
        except Exception:  # noqa: BLE001
            pass


def get_folder(folder_id: str):
    if _HAS_DATAIKU and folder_id:
        return _DkuFolder(folder_id)
    root = os.environ.get("WEBAPP_LOCAL_ROOT", os.path.abspath("./_webapp_local"))
    return _LocalFolder(os.path.join(root, folder_id or "config"))


def _config_folder_id() -> str:
    if _HAS_DATAIKU:  # pragma: no cover
        try:
            var = dataiku.get_custom_variables().get("WEBAPP_CONFIG_FOLDER")
            if var:
                return var
        except Exception:  # noqa: BLE001
            pass
    return os.environ.get("WEBAPP_CONFIG_FOLDER") or CONFIG_FOLDER_FALLBACK or "config"


def _config_folder():
    return get_folder(_config_folder_id())


# --------------------------------------------------------------------------- JSON IO
def _read_json(folder, name: str, default: Any = None) -> Any:
    try:
        return json.loads(folder.read_bytes("/" + name))
    except Exception:  # noqa: BLE001
        return default


def _write_json(folder, name: str, obj: Any) -> None:
    folder.write_bytes("/" + name, json.dumps(obj, indent=2, default=str).encode("utf-8"))


# --------------------------------------------------------------------------- settings
def default_settings() -> Dict[str, Any]:
    letters = list(string.ascii_uppercase[:N_DEFAULT_CATEGORIES])
    return {
        "admin": auth.default_admin(),
        "secret": auth.new_secret(),
        "categories": [{"id": c, "name": c, "order": i} for i, c in enumerate(letters)],
    }


def load_settings() -> Dict[str, Any]:
    folder = _config_folder()
    s = _read_json(folder, SETTINGS_FILE)
    if not s:
        s = default_settings()
        _write_json(folder, SETTINGS_FILE, s)
    return s


def save_settings(settings: Dict[str, Any]) -> None:
    _write_json(_config_folder(), SETTINGS_FILE, settings)


# --------------------------------------------------------------------------- recipes
def _recipe_name(cat_id: str) -> str:
    safe = "".join(ch for ch in cat_id if ch.isalnum() or ch in "-_")
    return f"category_{safe}.json"


def default_recipe(cat_id: str, name: Optional[str] = None) -> Dict[str, Any]:
    return {
        "id": cat_id, "name": name or cat_id,
        "folders": {"input": "", "mapping": "", "output": "", "template": ""},
        "data_sheet": "", "header_row": 0,
        "canonical_schema": [],
        "computed_columns": [],
        "lookups": [],
        "lookup_tables": {},
        "toggles": [],
        "comparison": [],
        "comparison_keys": [],
        "configured": False,
    }


def load_recipe(cat_id: str) -> Dict[str, Any]:
    r = _read_json(_config_folder(), _recipe_name(cat_id))
    if not r:
        settings = load_settings()
        name = next((c["name"] for c in settings["categories"] if c["id"] == cat_id), cat_id)
        return default_recipe(cat_id, name)
    base = default_recipe(cat_id)
    base.update(r)
    return base


def save_recipe(cat_id: str, recipe: Dict[str, Any]) -> None:
    recipe = dict(recipe)
    recipe["id"] = cat_id
    _write_json(_config_folder(), _recipe_name(cat_id), recipe)


def recipe_is_configured(recipe: Dict[str, Any]) -> bool:
    f = recipe.get("folders", {})
    return bool(
        recipe.get("canonical_schema")
        and recipe.get("computed_columns")
        and all(f.get(k) for k in ("input", "output"))
    )


# ------------------------------------------------------------------ managed folders
def list_project_managed_folders() -> List[Dict[str, str]]:
    if not _HAS_DATAIKU:
        return []
    try:  # pragma: no cover
        client = dataiku.api_client()
        project = client.get_project(dataiku.default_project_key())
        return [
            {"id": mf["id"], "name": mf.get("name", mf["id"])}
            for mf in project.list_managed_folders()
        ]
    except Exception:  # noqa: BLE001  # pragma: no cover
        return []


def folder_ok(folder_id: str) -> bool:
    if not folder_id:
        return False
    if not _HAS_DATAIKU:
        return True
    try:  # pragma: no cover
        get_folder(folder_id).list_paths()
        return True
    except Exception:  # noqa: BLE001
        return False


# --------------------------------------------------------------- category file ops
def list_files(folder_id: str, subdir: str = "") -> List[Dict[str, Any]]:
    if not folder_id:
        return []
    folder = get_folder(folder_id)
    out = []
    for p in folder.list_paths():
        rel = p.lstrip("/")
        if subdir and not rel.startswith(subdir.strip("/") + "/"):
            continue
        if not subdir and "/" in rel and rel.split("/")[0] == "_cache":
            continue
        out.append({"path": p, "name": rel.split("/")[-1]})
    return sorted(out, key=lambda d: d["name"].lower())


def read_file(folder_id: str, path: str) -> bytes:
    return get_folder(folder_id).read_bytes(path)


def write_file(folder_id: str, path: str, data: bytes) -> None:
    get_folder(folder_id).write_bytes(path, data)


def delete_file(folder_id: str, path: str) -> None:
    get_folder(folder_id).delete(path)


def clear_folder(folder_id: str, keep_prefixes: Optional[List[str]] = None) -> int:
    folder = get_folder(folder_id)
    n = 0
    for p in folder.list_paths():
        if keep_prefixes and any(p.lstrip("/").startswith(k) for k in keep_prefixes):
            continue
        folder.delete(p)
        n += 1
    return n

# ====================================================================================
# Flask backend
# ====================================================================================

"""Flask backend for the Dataiku "category formula & comparison" webapp.

Paste this into the webapp's **Python** pane. It expects the sibling package
``webapp_core`` to be importable - add ``webapp/python-lib`` to the project libraries
(Project > Libraries > Git/Filesystem) or copy ``python-lib/webapp_core`` into the
project's ``python-lib`` folder.

Deployment checklist is in ``webapp/README.md``.
"""


import io
import json
import traceback
from datetime import datetime
from functools import wraps



# Dataiku provides `app`; fall back to a standalone Flask app for local runs.
try:  # pragma: no cover
    app  # type: ignore  # noqa: F821
except NameError:  # pragma: no cover
    from flask import Flask
    app = Flask(__name__)

CACHE_DIR = "_cache"
COMPUTED_SUFFIX = "__computed.xlsx"


# --------------------------------------------------------------------------- helpers
def _err(msg, code=400):
    return jsonify({"ok": False, "error": str(msg)}), code


_MIME = {
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xls": "application/vnd.ms-excel",
    ".csv": "text/csv",
    ".json": "application/json",
}


def _send_bytes(data, filename):
    """Return a file download. Plain Response so it works on any Flask / Python version
    (send_file's keyword for the download name changed across 1.x / 2.x / 2.3)."""
    ext = ("." + filename.rsplit(".", 1)[1].lower()) if "." in filename else ""
    safe = filename.replace('"', "").replace("\n", "").replace("\r", "")
    return Response(
        bytes(data),
        mimetype=_MIME.get(ext, "application/octet-stream"),
        headers={
            "Content-Disposition": 'attachment; filename="%s"' % safe,
            "Content-Length": str(len(data)),
        },
    )


def _settings():
    return load_settings()


def require_admin(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        token = request.headers.get("X-Admin-Token", "")
        user = verify_token(token, _settings().get("secret", ""))
        if not user:
            return _err("admin authentication required", 401)
        request.admin_user = user  # type: ignore[attr-defined]
        return fn(*args, **kwargs)

    return wrapper


def _category(cat_id):
    settings = _settings()
    cat = next((c for c in settings["categories"] if c["id"] == cat_id), None)
    return cat


def _recipe_or_404(cat_id):
    if not _category(cat_id):
        return None, _err("unknown category", 404)
    return load_recipe(cat_id), None


def _base_name(path):
    return path.lstrip("/").split("/")[-1]


def _stem(name):
    n = _base_name(name)
    for suf in (COMPUTED_SUFFIX, ".xlsx", ".xls", ".csv", ".txt"):
        if n.lower().endswith(suf):
            return n[: -len(suf)]
    return n


# --------------------------------------------------------------------------- auth API
@app.route("/api/login", methods=["POST"])
def login():
    body = request.get_json(force=True, silent=True) or {}
    settings = _settings()
    adm = settings["admin"]
    if body.get("username") != adm["username"] or not verify_password(
        body.get("password", ""), adm["salt"], adm["hash"]
    ):
        return _err("invalid credentials", 401)
    token = make_token(adm["username"], settings["secret"])
    return jsonify({"ok": True, "token": token, "must_change": adm.get("must_change", False)})


@app.route("/api/admin/change-credentials", methods=["POST"])
@require_admin
def change_credentials():
    body = request.get_json(force=True, silent=True) or {}
    settings = _settings()
    adm = settings["admin"]
    if not verify_password(body.get("current_password", ""), adm["salt"], adm["hash"]):
        return _err("current password is wrong", 403)
    new_pw = body.get("new_password", "")
    if len(new_pw) < 6:
        return _err("new password must be at least 6 characters")
    salt, h = hash_password(new_pw)
    settings["admin"] = {
        "username": body.get("new_username") or adm["username"],
        "salt": salt, "hash": h, "must_change": False,
    }
    save_settings(settings)
    return jsonify({"ok": True})


# --------------------------------------------------------------------- categories API
@app.route("/api/categories", methods=["GET"])
def categories():
    settings = _settings()
    out = []
    for cat in sorted(settings["categories"], key=lambda c: c.get("order", 0)):
        recipe = load_recipe(cat["id"])
        out.append({
            "id": cat["id"], "name": cat["name"],
            "configured": recipe_is_configured(recipe),
            "n_canonical": len(recipe.get("canonical_schema", [])),
            "n_computed": len(recipe.get("computed_columns", [])),
            "folders_wired": all(recipe.get("folders", {}).get(k)
                                 for k in ("input", "mapping", "output", "template")),
        })
    return jsonify({"ok": True, "categories": out})


@app.route("/api/admin/folders", methods=["GET"])
@require_admin
def admin_folders():
    return jsonify({"ok": True, "folders": list_project_managed_folders()})


@app.route("/api/admin/category/<cat_id>", methods=["GET"])
@require_admin
def admin_get_category(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    return jsonify({"ok": True, "recipe": recipe})


@app.route("/api/admin/category/<cat_id>/rename", methods=["POST"])
@require_admin
def admin_rename(cat_id):
    body = request.get_json(force=True, silent=True) or {}
    new_name = (body.get("name") or "").strip()
    if not new_name:
        return _err("name required")
    settings = _settings()
    for cat in settings["categories"]:
        if cat["id"] == cat_id:
            cat["name"] = new_name
            save_settings(settings)
            recipe = load_recipe(cat_id)
            recipe["name"] = new_name
            save_recipe(cat_id, recipe)
            return jsonify({"ok": True})
    return _err("unknown category", 404)


@app.route("/api/admin/category/<cat_id>/folders", methods=["POST"])
@require_admin
def admin_set_folders(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    body = request.get_json(force=True, silent=True) or {}
    folders = body.get("folders", {})
    bad = [k for k, v in folders.items() if v and not folder_ok(v)]
    if bad:
        return _err("folder id not found / not readable: " + ", ".join(bad))
    recipe["folders"] = {k: folders.get(k, recipe["folders"].get(k, ""))
                         for k in ("input", "mapping", "output", "template")}
    save_recipe(cat_id, recipe)
    return jsonify({"ok": True, "recipe": recipe})


@app.route("/api/admin/category/<cat_id>/sample", methods=["POST"])
@require_admin
def admin_upload_sample(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    if "file" not in request.files:
        return _err("no file uploaded")
    f = request.files["file"]
    data = f.read()
    data_sheet = request.form.get("data_sheet") or None
    try:
        analysis = analyze_sample(data, data_sheet=data_sheet)
        tables = lookups_from_sample(analysis, data)
    except Exception as exc:  # noqa: BLE001
        return _err(f"could not parse sample: {exc}")

    # keep the raw sample for re-parsing later
    get_folder(_config_folder_id()).write_bytes(f"/samples/{cat_id}.xlsx", data)

    analysis["lookup_tables"] = tables
    analysis["comparison_candidates"] = [c["name"] for c in analysis["computed_columns"]]
    return jsonify({"ok": True, "analysis": analysis, "filename": f.filename})


@app.route("/api/admin/category/<cat_id>/recipe", methods=["POST"])
@require_admin
def admin_save_recipe(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    body = request.get_json(force=True, silent=True) or {}
    incoming = body.get("recipe", {})

    for key in ("data_sheet", "header_row", "canonical_schema", "computed_columns",
                "lookups", "lookup_tables", "toggles", "comparison", "comparison_keys"):
        if key in incoming:
            recipe[key] = incoming[key]
    if "folders" in incoming:
        recipe["folders"].update({k: v for k, v in incoming["folders"].items()})
    recipe["name"] = _category(cat_id)["name"]

    # reference-resolution check
    problems = _check_references(recipe)
    if problems and not body.get("force"):
        return jsonify({"ok": False, "needs_confirmation": True, "problems": problems})

    recipe["configured"] = recipe_is_configured(recipe)
    save_recipe(cat_id, recipe)

    # mirror lookup tables into the mapping folder as CSV (human-readable)
    map_folder = recipe["folders"].get("mapping")
    if map_folder:
        for name, spec in (recipe.get("lookup_tables") or {}).items():
            try:
                df = pd.DataFrame(spec["records"], columns=spec["headers"])
                write_file(map_folder, f"/{name}.csv",
                              df.to_csv(index=False).encode("utf-8"))
            except Exception:  # noqa: BLE001
                pass
    return jsonify({"ok": True, "recipe": recipe, "problems": problems})


def _check_references(recipe):
    canon = {c.lower() for c in recipe.get("canonical_schema", [])}
    comp = {c["name"].lower() for c in recipe.get("computed_columns", [])}
    lookups = set(recipe.get("lookup_tables") or {})
    toggles = {t["name"] for t in recipe.get("toggles", [])}
    problems = []
    for c in recipe.get("computed_columns", []):
        refs = c.get("refs") or extract_refs(c.get("excel_formula", ""))
        for sh in refs.get("sheets", []):
            if sh not in lookups:
                problems.append(f"{c['name']}: lookup sheet '{sh}' is not stored")
        for tok in refs.get("tokens", []):
            tl = tok.lower()
            if tl in canon or tl in comp or tok in lookups or tok in toggles:
                continue
            problems.append(f"{c['name']}: unresolved reference '{tok}' (define a toggle?)")
    for rule in recipe.get("comparison", []):
        for side in ("left", "right"):
            col = (rule.get(side) or "").lower()
            if col and col not in canon and col not in comp:
                problems.append(f"comparison: column '{rule.get(side)}' does not exist")
    return problems


# ----------------------------------------------------------------- category runtime
@app.route("/api/category/<cat_id>/upload", methods=["POST"])
def upload_inputs(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    folder = recipe["folders"].get("input")
    if not folder:
        return _err("this category has no input folder wired yet")
    saved = []
    for f in request.files.getlist("files"):
        name = _base_name(f.filename or "upload")
        write_file(folder, "/" + name, f.read())
        saved.append(name)
    return jsonify({"ok": True, "saved": saved})


@app.route("/api/category/<cat_id>/files", methods=["GET"])
def list_category_files(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    which = request.args.get("folder", "input")
    folder = recipe["folders"].get(which)
    files = [x for x in list_files(folder) if not x["name"].startswith(".")]
    files = [x for x in files if CACHE_DIR + "/" not in x["path"]]
    return jsonify({"ok": True, "folder": which, "files": files})


@app.route("/api/category/<cat_id>/validate", methods=["POST"])
def validate_inputs(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    if not recipe.get("canonical_schema"):
        return _err("category has no schema yet - set it up in Admin")
    folder = recipe["folders"].get("input")
    results = []
    for item in list_files(folder):
        try:
            data = read_file(folder, item["path"])
            df, hr = read_table(data, item["name"])
            v = validate_schema(list(df.columns), recipe["canonical_schema"])
            results.append({"file": item["name"], "header_row": hr, "rows": len(df), **v})
        except Exception as exc:  # noqa: BLE001
            results.append({"file": item["name"], "ok": False, "message": str(exc)})
    return jsonify({"ok": True, "results": results})


@app.route("/api/category/<cat_id>/compute", methods=["POST"])
def run_compute(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    if not recipe_is_configured(recipe):
        return _err("category is not fully configured")
    body = request.get_json(force=True, silent=True) or {}
    only = set(body.get("files") or [])
    in_folder = recipe["folders"]["input"]
    out_folder = recipe["folders"]["output"]
    tpl_folder = recipe["folders"].get("template") or out_folder
    lookups = Lookups(recipe.get("lookup_tables") or {})

    results = []
    for item in list_files(in_folder):
        if only and item["name"] not in only:
            continue
        try:
            data = read_file(in_folder, item["path"])
            df, _ = read_table(data, item["name"])
            v = validate_schema(list(df.columns), recipe["canonical_schema"])
            if not v["ok"]:
                results.append({"file": item["name"], "ok": False, "message": v["message"]})
                continue
            values = evaluate(df, recipe, lookups)
            wb = build_workbook(values, recipe, lookups,
                                       data_sheet_name=recipe.get("data_sheet") or "Data")
            stem = _stem(item["name"])
            out_name = f"{stem}{COMPUTED_SUFFIX}"
            write_file(out_folder, "/" + out_name, wb)
            write_file(tpl_folder, "/" + out_name, wb)
            write_file(out_folder, f"/{CACHE_DIR}/{stem}.json",
                          values.to_json(orient="split", date_format="iso").encode("utf-8"))
            results.append({
                "file": item["name"], "ok": True, "output": out_name,
                "rows": len(values), "errors": values.attrs.get("compute_errors", []),
            })
        except Exception as exc:  # noqa: BLE001
            traceback.print_exc()
            results.append({"file": item["name"], "ok": False, "message": str(exc)})
    return jsonify({"ok": True, "results": results})


@app.route("/api/category/<cat_id>/compare", methods=["POST"])
def run_compare(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    if not recipe.get("comparison"):
        return _err("no comparison rules configured for this category")
    out_folder = recipe["folders"]["output"]
    in_folder = recipe["folders"]["input"]
    lookups = Lookups(recipe.get("lookup_tables") or {})

    files = []
    for item in list_files(out_folder):
        if not item["name"].endswith(COMPUTED_SUFFIX):
            continue
        stem = _stem(item["name"])
        try:
            cached = read_file(out_folder, f"/{CACHE_DIR}/{stem}.json")
            vdf = pd.read_json(io.BytesIO(cached), orient="split")
        except Exception:  # noqa: BLE001 - recompute from the matching input
            src = next((i for i in list_files(in_folder) if _stem(i["name"]) == stem), None)
            if not src:
                continue
            df, _ = read_table(read_file(in_folder, src["path"]), src["name"])
            vdf = evaluate(df, recipe, lookups)
        files.append((item["name"], vdf))

    if not files:
        return _err("no computed outputs found - run compute first")
    wb = build_comparison_workbook(files, recipe)
    ts = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    name = f"comparison__{ts}.xlsx"
    write_file(out_folder, "/" + name, wb)
    summary = run_comparison(files, recipe)["Summary"]
    return jsonify({"ok": True, "output": name,
                    "summary": json.loads(summary.to_json(orient="records"))})


@app.route("/api/category/<cat_id>/download", methods=["GET"])
def download(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    which = request.args.get("folder", "output")
    path = request.args.get("path", "")
    folder = recipe["folders"].get(which)
    if not folder or not path:
        return _err("folder and path required")
    try:
        data = read_file(folder, path)
    except Exception as exc:  # noqa: BLE001
        return _err(f"not found: {exc}", 404)
    return _send_bytes(data, _base_name(path))


@app.route("/api/category/<cat_id>/delete", methods=["POST"])
def delete(cat_id):
    recipe, err = _recipe_or_404(cat_id)
    if err:
        return err
    body = request.get_json(force=True, silent=True) or {}
    which = body.get("folder", "")
    folder = recipe["folders"].get(which)
    if not folder:
        return _err("unknown folder")
    if body.get("all"):
        n = clear_folder(folder)
        return jsonify({"ok": True, "deleted": n})
    path = body.get("path", "")
    if not path:
        return _err("path required")
    delete_file(folder, path)
    # drop the sidecar cache for computed outputs
    if path.lstrip("/").endswith(COMPUTED_SUFFIX):
        delete_file(folder, f"/{CACHE_DIR}/{_stem(path)}.json")
    return jsonify({"ok": True, "deleted": 1})


@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({"ok": True, "time": datetime.utcnow().isoformat() + "Z"})
